version: "3"
services:
  person-crud-backend:
    image: ccyprus/personcrud:v2
    ports:
      - "8086:8086"
    networks:
      - person-network
    depends_on:
      - person-mysql-db
 
  person-mysql-db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - person-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
      
  adminer:
    image: adminer
    restart: always
    networks:
      - person-network
    ports:
      - 8080:8080 

volumes:
  init:  
networks:
  person-network: